config/routes.rb
Rails.application.routes.draw do
  resources :studentsections
  resources :studentclasses
  resources :coursecodes
  resources :batches
  devise_for :users
  root "courses#index"
  resources :courses do
    collection do
      get :showall
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/studentclasses_controller.rb
class StudentclassesController < ApplicationController
  before_action :set_studentclass, only: [:show, :edit, :update, :destroy]

  # GET /studentclasses
  # GET /studentclasses.json
  def index
    @studentclasses = Studentclass.all
  end

  # GET /studentclasses/1
  # GET /studentclasses/1.json
  def show
  end

  # GET /studentclasses/new
  def new
    @studentclass = Studentclass.new
  end

  # GET /studentclasses/1/edit
  def edit
  end

  # POST /studentclasses
  # POST /studentclasses.json
  def create
    @studentclass = Studentclass.new(studentclass_params)

    respond_to do |format|
      if @studentclass.save
        format.html { redirect_to @studentclass, notice: 'Studentclass was successfully created.' }
        format.json { render :show, status: :created, location: @studentclass }
      else
        format.html { render :new }
        format.json { render json: @studentclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studentclasses/1
  # PATCH/PUT /studentclasses/1.json
  def update
    respond_to do |format|
      if @studentclass.update(studentclass_params)
        format.html { redirect_to @studentclass, notice: 'Studentclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @studentclass }
      else
        format.html { render :edit }
        format.json { render json: @studentclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentclasses/1
  # DELETE /studentclasses/1.json
  def destroy
    @studentclass.destroy
    respond_to do |format|
      format.html { redirect_to studentclasses_url, notice: 'Studentclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studentclass
      @studentclass = Studentclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studentclass_params
      params.require(:studentclass).permit(:studentclass)
    end
end

app/helpers/studentclasses_helper.rb
module StudentclassesHelper
end

app/views/studentclasses/_form.html.erb
<%= form_for @studentclass, :html => { :class => "form-horizontal studentclass" } do |f| %>

  <% if @studentclass.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@studentclass.errors.count, "error") %> prohibited this studentclass from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @studentclass.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :studentclass, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :studentclass, :class => 'form-control' %>
    </div>
    <%=f.error_span(:studentclass) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                studentclasses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/studentclasses/edit.html.erb
<%- model_class = Studentclass -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/studentclasses/index.html.erb
<%- model_class = Studentclass -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:studentclass) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @studentclasses.each do |studentclass| %>
      <tr>
        <td><%= link_to studentclass.id, studentclass_path(studentclass) %></td>
        <td><%= studentclass.studentclass %></td>
        <td><%=l studentclass.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_studentclass_path(studentclass), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      studentclass_path(studentclass),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_studentclass_path,
            :class => 'btn btn-primary' %>

app/views/studentclasses/new.html.erb
<%- model_class = Studentclass -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/studentclasses/show.html.erb
<%- model_class = Studentclass -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:studentclass) %>:</strong></dt>
  <dd><%= @studentclass.studentclass %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              studentclasses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_studentclass_path(@studentclass), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              studentclass_path(@studentclass),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>