config/routes.rb
Rails.application.routes.draw do
  resources :studentsections
  resources :studentclasses
  resources :coursecodes
  resources :batches
  devise_for :users
  root "courses#index"
  resources :courses do
    collection do
      get :showall
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coursecode.rb
class Coursecode < ApplicationRecord
  has_many :courses
end

app/controllers/coursecodes_controller.rb
class CoursecodesController < ApplicationController
  before_action :set_coursecode, only: [:show, :edit, :update, :destroy]

  # GET /coursecodes
  # GET /coursecodes.json
  def index
    @coursecodes = Coursecode.all
  end

  # GET /coursecodes/1
  # GET /coursecodes/1.json
  def show
  end

  # GET /coursecodes/new
  def new
    @coursecode = Coursecode.new
  end

  # GET /coursecodes/1/edit
  def edit
  end

  # POST /coursecodes
  # POST /coursecodes.json
  def create
    @coursecode = Coursecode.new(coursecode_params)

    respond_to do |format|
      if @coursecode.save
        format.html { redirect_to @coursecode, notice: 'Coursecode was successfully created.' }
        format.json { render :show, status: :created, location: @coursecode }
      else
        format.html { render :new }
        format.json { render json: @coursecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coursecodes/1
  # PATCH/PUT /coursecodes/1.json
  def update
    respond_to do |format|
      if @coursecode.update(coursecode_params)
        format.html { redirect_to @coursecode, notice: 'Coursecode was successfully updated.' }
        format.json { render :show, status: :ok, location: @coursecode }
      else
        format.html { render :edit }
        format.json { render json: @coursecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coursecodes/1
  # DELETE /coursecodes/1.json
  def destroy
    @coursecode.destroy
    respond_to do |format|
      format.html { redirect_to coursecodes_url, notice: 'Coursecode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coursecode
      @coursecode = Coursecode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coursecode_params
      params.require(:coursecode).permit(:codename)
    end
end

app/helpers/coursecodes_helper.rb
module CoursecodesHelper
end

app/views/coursecodes/_form.html.erb
<%= form_for @coursecode, :html => { :class => "form-horizontal coursecode" } do |f| %>

  <% if @coursecode.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@coursecode.errors.count, "error") %> prohibited this coursecode from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @coursecode.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codename, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :codename, :class => 'form-control' %>
    </div>
    <%=f.error_span(:codename) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                coursecodes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/coursecodes/edit.html.erb
<%- model_class = Coursecode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/coursecodes/index.html.erb
<%- model_class = Coursecode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:codename) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @coursecodes.each do |coursecode| %>
      <tr>
        <td><%= link_to coursecode.id, coursecode_path(coursecode) %></td>
        <td><%= coursecode.codename %></td>
        <td><%=l coursecode.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_coursecode_path(coursecode), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      coursecode_path(coursecode),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_coursecode_path,
            :class => 'btn btn-primary' %>

app/views/coursecodes/new.html.erb
<%- model_class = Coursecode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/coursecodes/show.html.erb
<%- model_class = Coursecode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:codename) %>:</strong></dt>
  <dd><%= @coursecode.codename %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              coursecodes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_coursecode_path(@coursecode), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              coursecode_path(@coursecode),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>