config/routes.rb
Rails.application.routes.draw do
  resources :studentsections
  resources :studentclasses
  resources :coursecodes
  resources :batches
  devise_for :users
  root "courses#index"
  resources :courses do
    collection do
      get :showall
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/studentsection.rb
class Studentsection < ApplicationRecord
  has_many :courses
end

app/controllers/studentsections_controller.rb
class StudentsectionsController < ApplicationController
  before_action :set_studentsection, only: [:show, :edit, :update, :destroy]

  # GET /studentsections
  # GET /studentsections.json
  def index
    @studentsections = Studentsection.all
  end

  # GET /studentsections/1
  # GET /studentsections/1.json
  def show
  end

  # GET /studentsections/new
  def new
    @studentsection = Studentsection.new
  end

  # GET /studentsections/1/edit
  def edit
  end

  # POST /studentsections
  # POST /studentsections.json
  def create
    @studentsection = Studentsection.new(studentsection_params)

    respond_to do |format|
      if @studentsection.save
        format.html { redirect_to @studentsection, notice: 'Studentsection was successfully created.' }
        format.json { render :show, status: :created, location: @studentsection }
      else
        format.html { render :new }
        format.json { render json: @studentsection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studentsections/1
  # PATCH/PUT /studentsections/1.json
  def update
    respond_to do |format|
      if @studentsection.update(studentsection_params)
        format.html { redirect_to @studentsection, notice: 'Studentsection was successfully updated.' }
        format.json { render :show, status: :ok, location: @studentsection }
      else
        format.html { render :edit }
        format.json { render json: @studentsection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentsections/1
  # DELETE /studentsections/1.json
  def destroy
    @studentsection.destroy
    respond_to do |format|
      format.html { redirect_to studentsections_url, notice: 'Studentsection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studentsection
      @studentsection = Studentsection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studentsection_params
      params.require(:studentsection).permit(:studentsection)
    end
end

app/helpers/studentsections_helper.rb
module StudentsectionsHelper
end

app/views/studentsections/_form.html.erb
<%= form_for @studentsection, :html => { :class => "form-horizontal studentsection" } do |f| %>

  <% if @studentsection.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@studentsection.errors.count, "error") %> prohibited this studentsection from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @studentsection.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :studentsection, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :studentsection, :class => 'form-control' %>
    </div>
    <%=f.error_span(:studentsection) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                studentsections_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/studentsections/edit.html.erb
<%- model_class = Studentsection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/studentsections/index.html.erb
<%- model_class = Studentsection -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:studentsection) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @studentsections.each do |studentsection| %>
      <tr>
        <td><%= link_to studentsection.id, studentsection_path(studentsection) %></td>
        <td><%= studentsection.studentsection %></td>
        <td><%=l studentsection.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_studentsection_path(studentsection), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      studentsection_path(studentsection),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_studentsection_path,
            :class => 'btn btn-primary' %>

app/views/studentsections/new.html.erb
<%- model_class = Studentsection -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/studentsections/show.html.erb
<%- model_class = Studentsection -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:studentsection) %>:</strong></dt>
  <dd><%= @studentsection.studentsection %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              studentsections_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_studentsection_path(@studentsection), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              studentsection_path(@studentsection),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>