config/routes.rb
Rails.application.routes.draw do
  resources :studentsections
  resources :studentclasses
  resources :coursecodes
  resources :batches
  devise_for :users
  root "courses#index"
  resources :courses do
    collection do
      get :showall
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /courses
  # GET /courses.json
  def index

  end

  # GET /cources/showall
  def showall
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_user.courses.build(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:coursename, :responsibleperson, :duration,
        :description, :user_id, :coursecode_id, :startdate, :enddate,
        :batch_id, :studentclass_id,
        :studentsection_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, :html => { :class => "form-horizontal course" } do |f| %>

  <% if @course.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :coursename, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coursename, :class => 'form-control' %>
    </div>
    <%=f.error_span(:coursename) %>
  </div>
  <div class="form-group">
    <%= f.label :responsibleperson, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :responsibleperson, :class => 'form-control' %>
    </div>
    <%=f.error_span(:responsibleperson) %>
  </div>
  <div class="form-group">
    <%= f.label :duration, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :duration, :class => 'form-control' %>
    </div>
    <%=f.error_span(:duration) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <%= f.label :studentclass_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:course, :studentclass_id, Studentclasses.all, :studentclass), class: 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Save course", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                showall_courses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => t("helpers.titles.index") %></h1>
</div>

<%= link_to t('.new', :default => t("Course")), showall_courses_path, :class => 'btn btn-primary' %>

<%= link_to t('.new', :default => t("Batch")), batches_path, :class => 'btn btn-primary' %>

<%= link_to t('.new', :default => t("Class")), studentclasses_path, :class => 'btn btn-primary' %>

<%= link_to t('.new', :default => t("Section")),  studentsections_path, :class => 'btn btn-primary' %>

<%= link_to t('.new', :default => t("Code")), coursecodes_path, :class => 'btn btn-primary' %>

<%= link_to t('.new', :default => t("Chapters")), new_course_path, :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:coursename) %>:</strong></dt>
  <dd><%= @course.coursename %></dd>
  <dt><strong><%= model_class.human_attribute_name(:responsibleperson) %>:</strong></dt>
  <dd><%= @course.responsibleperson %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @course.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @course.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @course.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              courses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              course_path(@course),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/courses/showall.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:coursename) %></th>
      <th><%= model_class.human_attribute_name(:responsibleperson) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.id, course_path(course) %></td>
        <td><%= course.coursename %></td>
        <td><%= course.responsibleperson %></td>
        <td><%= course.duration %></td>
        <td><%= course.description %></td>
        <td><%= course.user.email %></td>
        <td><%=l course.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_course_path(course), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      course_path(course),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_course_path, :class => 'btn btn-primary' %>